### ISSUE TITLE
Export to Excel function not working for Motif Based Peptide scorer

### ISSUE THREAD

**Issue by danielconoleUoA** [EmineTopcu/PeSA#5]
Thanks for the very useful program! It just says there is a problem every time I try to export the excel file from this analysis. Cna you check and fix this please? Many thanks.

**Comment by danielconoleUoA** [comment]
I am also not sure how to load a negative motif for this function. Can you please help?

**Comment by EmineTopcu** [comment]
Thanks for the issue report. You are right, there seems to be a bug in the Motif Based Peptide Scorer. I will try to install a fix within a couple of days.

**Comment by EmineTopcu** [comment]
Hi again,
I released a new version: 2.2.2. There was a bug in loading the motif file, which is probably why you had problems in loadng the negative motif (as a motif file holds both the positive and negative motifs).
Let me know if you still have issues.
Thanks

**Comment by danielconoleUoA** [comment]
Dear Emine,

Thank you for your efforts with this. Despite downloading the new version (2.2.2) – I still have the same problems. Are there background files that I need to delete to ensure my PeSa version is up to date? Below is the error message I get when I try to export a peptide scorer output file:

***@***.***
Thanks,
Daniel

**Comment by EmineTopcu** [comment]
HI Daniel,

The error message you attached does not show up. Are you attaching a screenshot? Do you mind sending it as text?

There is only one executable file and no installation, so no need to clear up the old version. Are you still having problems with seeing the negative motif? I realized I haven't updated the About form (I am on vacation right now, working on a very small screen), but if you are running PeSA.Windows_2.2.2_64bit.exe (Or the 32 bit version), the old executable will not have any impact.

**Comment by danielconoleUoA** [comment]
Hi Emine,

Thanks for your reply, especially while on holiday! Yup using the new exe 2.2.2. file, it still show the same following error (also attached as a word doc this time):

“There is a problem with creating the export file. Please try again.”

Still also having problems seeing the negative motif, not sure what I am doing wrong (I do have negative values in my input data).

Thanks,
Daniel

**Comment by EmineTopcu** [comment]
Hi Daniel,

A new version is released, where the export to excel bug is fixed for frequency based motifs. Please let me know if the problem still continues.

Thanks
